### ISSUE TITLE
lambda integration interest?

### ISSUE THREAD

**Issue by dstokes** [24HOURSMEDIA/node-aws-cloudfront-sg#17]
i've added lambda support as a feature for this lib. if there's interest i can open a pr from https://github.com/Fullscreen/node-aws-cloudfront-sg/tree/feature/lambda

**Comment by 24HOURSMEDIA** [comment]
Thank you, I'm interested in a pull request. However, I will not actively maintain the project;

AWS now seems to provide their own very similar lambda function, which also listens to an SNS topic 'AmazonIpSpaceChanged'. I feel AWS can provide better support. [see this page on git](https://github.com/awslabs/aws-cloudfront-samples/tree/master/update_security_groups_lambda)

Additionally, it is now possible to add custom headers from Edge locations, allowing to pass a 'secret' and verify this in the backends: http://www.24hoursmedia.com/2016/01/23/protect-cloudfront-nginx/

The combination of these two techniques would be very effective.

Again, thanks for your contributions!

**Comment by dstokes** [comment]
had no idea about the ip space change SNS topic. i'll have to take a look at that. thanks!

**Comment by 24HOURSMEDIA** [comment]
Me neither, they are pretty recent features I guess. The topic ('cloudfront security group') has been present for a long period on their forums, I am glad AWS appears to take initiative for some support for that.

Again thank you for the contributions and interest in the project.

Regards,

Mike
